



ALTER TABLE "SKU" DROP CONSTRAINT "SKU_createdById_fkey";

ALTER TABLE "SKU" ALTER COLUMN "createdById" SET NOT NULL;

ALTER TABLE "SKU" ADD CONSTRAINT "SKU_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE NO ACTION;